name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -yy apt-utils
          sudo apt-get install -yy curl gcc git bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev hwloc libhwloc-dev
#          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y
      - name: Build
        run: |
          export PATH=~/.cargo/bin:$PATH
          echo "machine github.com login $TOKEN password x-oauth-basic" > ~/.netrc
          make build
        env:
          TOKEN: ${{ secrets.PECORINO_READ_TOKEN }}

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -yy apt-utils
          sudo apt-get install -yy curl gcc git bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev hwloc libhwloc-dev
#          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path --default-toolchain none -y
      - name: Build
        run: |
          export PATH=~/.cargo/bin:$PATH
          echo "machine github.com login $TOKEN password x-oauth-basic" > ~/.netrc
          make build
        env:
          TOKEN: ${{ secrets.PECORINO_READ_TOKEN }}
      - name: ModTidy check
        run: make check-modtidy
      - name: Lint check
        run: |
          make install_lint
          make lint